### ISSUE TITLE
Add pc_id constituency code for shape joins

### ISSUE THREAD

**Issue by planemad** [Vonter/india-election-affidavits#1]
To match the CSV records to [available shapefiles ](https://github.com/datameet/maps/blob/master/parliamentary-constituencies/india_pc_2019_simplified.geojson), it would be useful to add the matching `pc_id` value to each record since the names do not perfectly line up. 

Have created a name -> pc_id mapping for the 2019 elections in [this table](https://docs.google.com/spreadsheets/d/1WTP4L20lmC-mdaf8b6_9PKSPC_tjK6C900_Ck0nKbUo/edit?usp=sharing)

cc @Vonter

**Comment by Vonter** [comment]
Thanks for the mapping table @planemad 

I've added a new CSV which includes the `pc_id` column: https://github.com/Vonter/india-election-affidavits/blob/main/extended/shapefile.csv

**Comment by planemad** [comment]
2014 mappings will take some more time. Will share once its ready.
